{% set name = "rocrate" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/rocrate-{{ version }}.tar.gz
  sha256: eafd31adf0f6c0603eb68ff6e0f1f9f82028f7ffd345a7fe485eecee8240d485

build:
  entry_points:
    - rocrate=rocrate.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - arcp ==0.2.1
    - jinja2
    - python-dateutil
    - click

test:
  imports:
    - rocrate
  commands:
    - rocrate --help
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/ResearchObject/ro-crate-py/
  summary: RO-Crate metadata generator/parser
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mirpedrol
    - mashehu
    - ewels
    - stain
    - elichad
